LoginUser/LoginUser/urls.py
from django.contrib import admin
from django.urls import path ,include
from lo_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('user/',include('lo_app.urls')),
    path('logout/',views.user_logout,name='logout')


]

LoginUser/lo_app/urls.py
from django.urls import path,include
from . import views

app_name='lo_app'
urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='login')
]

LoginUser/lo_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

LoginUser/lo_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

LoginUser/lo_app/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import  authenticate,login,logout
# Create your views here.
def index(request):
    return render(request,'lo_app/index.html')

def register(request):
    registered = False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pics' in request.FILES:
                profile.profile_pic=request.FILES['profile_pics']
            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request,'lo_app/register.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return  HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Not active")
        else:
            print("failed")
            print("Username:{} and password{}".format(username,password))
            return HttpResponse("invalid")
    else:
        return render(request,'lo_app/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return  HttpResponseRedirect(reverse('index'))

LoginUser/templates/lo_app/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="#">Welcome</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{%url 'index'%}">Index</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{%url 'lo_app:register'%}">Register</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
    </li>
    {%if user.is_authenticated%}
    <li class="nav-item">
      <a class="nav-link" href="{%url 'logout'%}">Logout</a>
    </li>
    {%else%}
    <li class="nav-item">
      <a class="nav-link" href="{%url 'lo_app:login'%}">Login</a>
    </li>
    {%endif%}
  </ul>
</nav>

{%block body_block%}
{%endblock%}
</body>
</html>

LoginUser/templates/lo_app/index.html
<!DOCTYPE html>
{%extends 'lo_app/base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block body_block%}
<div class="container">
    <h1 class="text-info text-center">You are at Index</h1>
    <div class="jumbotron">
    <h1>Hello from index</h1>
    </div>
</div>

{%endblock%}
</body>
</html>

LoginUser/templates/lo_app/login.html
<!DOCTYPE html>
{%extends 'lo_app/base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block body_block%}
<div class="container">
    <div class="jumbotron">
        <h1>Please Log in</h1>
        <form action="{%url 'lo_app:login' %}" method="post">
            {%csrf_token%}
            <label for="username">Username:</label>
            <input type="text" name="username">
            <label for="password">Password</label>
            <input type="password" name="password">
            <input type="submit" value="login">
        </form>
    </div>
</div>
{%endblock%}
</body>
</html>

LoginUser/templates/lo_app/register.html
<!DOCTYPE html>
{%extends 'lo_app/base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block body_block%}
<div class="container">
    <div class="jumbotron">
        {%if registered%}
        <h1>Thank you for registering</h1>
        {%else%}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p}}
            {{ profile_form.as_p}}
            <input type="submit" value="Register">
        </form>
        {%endif%}
    </div>
</div>
{%endblock%}
</body>
</html>